/**
 * Static UI strings (UI Spec §25). Fixed Chinese copy — a single module,
 * used verbatim everywhere. Tool rows read per-tool verbs from toolMeta.ts.
 */
export const copy = {
  "app.title": "DSH Life Assistant",
  "app.domain": "Chinook Music",
  "empty.headline": "今天想听点什么？",
  "empty.sub": "搜索音乐、获取推荐，或者查看你在 Chinook 的订单。数据来自真实目录，回答由 AI 助手一步步完成。",
  "empty.chip.queen": "帮我找 Queen 的专辑",
  "empty.chip.jazz": "推荐一些爵士乐",
  "empty.chip.orders": "查看我的最近订单",
  newSession: "新会话",
  "composer.placeholder": "问点什么…",
  "composer.hint": "Enter 发送，Shift + Enter 换行",
  "composer.sending": "Agent 正在回答…",
  "composer.sendFailed": "发送失败，请重试",
  "composer.counter": "{n}/4000",
  "sidebar.group.today": "今天",
  "sidebar.group.yesterday": "昨天",
  "sidebar.group.earlier": "更早",
  "sidebar.untitled": "新会话",
  "sidebar.switchLocked": "请等待当前回答完成",
  "sidebar.open": "会话列表",
  "activity.button": "活动",
  "activity.title": "活动事件",
  "activity.empty": "暂无活动事件",
  "activity.filter.all": "全部",
  "activity.filter.tools": "工具",
  understanding: "正在理解你的请求…",
  "strip.done": "完成 · 使用 {n} 个工具",
  "strip.stopped": "已停止 · 使用 {n} 个工具",
  "strip.failed": "出错了 · 使用 {n} 个工具",
  "strip.expand": "展开",
  "strip.collapse": "收起",
  "strip.noAnswer": "未生成回答",
  "detail.open": "查看详情",
  "detail.close": "收起详情",
  "detail.args": "参数",
  "detail.result": "结果",
  "detail.duration": "耗时",
  "detail.status": "状态",
  "detail.statusOk": "成功",
  "bubble.caption.limited": "回答达到长度上限",
  "bubble.caption.stopped": "已停止生成",
  "bubble.caption.interrupted": "上次回答未完成",
  "bubble.caption.failed": "回答中断",
  "scroll.backToLatest": "回到最新消息",
  "restore.loading": "正在恢复会话…",
  "restore.failed": "会话恢复失败",
  "restore.retry": "重试",
  "restore.close": "关闭",
  "archive.older": "…更早的 {n} 条消息已归档",
  "status.starting": "正在启动…",
  "status.ready": "Agent 已连接",
  "status.restoring": "正在恢复…",
  "status.disconnected": "已断开",
  "status.error": "错误",
  "status.restarting": "正在重新启动…",
  "status.busy": "Agent 正在回答…",
  "status.model": "deepseek-v4-flash · 会话已自动保存",
  "card.starting.title": "正在启动 DSH Life Assistant…",
  "card.disconnected.title": "Agent Runtime 已断开",
  "card.disconnected.sub": "与 Agent 的连接意外中断。你的会话已保存在本机，不会丢失。",
  "card.disconnected.action": "重新连接",
  "card.error.title": "出问题了",
  "card.error.action": "重新启动",
  "card.error.retryFailed": "重试失败，请稍后再试",
  // §17.1 business error captions by code
  "err.tool.accessDenied": "无法访问该内容",
  "err.tool.identityRequired": "需要客户身份",
  "err.tool.notFound": "未找到相关数据",
  "err.tool.invalidArgument": "请求参数无效",
  "err.tool.data": "数据服务异常",
  "err.tool.unknown": "操作失败",
  // §17.2 turn-level failures
  "err.turn.generation": "回答生成失败",
  "err.turn.unknown": "未知错误",
  // §23.4: announced prefix for the once-announced error line `出了错：{caption}`.
  "err.announce": "出了错：",
  "provenance.assistant": "Chinook Music",
} as const;

export type CopyKey = keyof typeof copy;

export function stripCopy(kind: "done" | "stopped" | "failed", n: number): string {
  const key = kind === "done" ? "strip.done" : kind === "stopped" ? "strip.stopped" : "strip.failed";
  return copy[key].replace("{n}", String(n));
}
